# Generated by Django 3.0.3 on 2020-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200407_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
