# Generated by Django 3.0.3 on 2020-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200514_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='ordernr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
