# Generated by Django 3.0.3 on 2020-04-07 16:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200331_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
