# Generated by Django 3.0.3 on 2020-05-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
    ]
